{% set version = "2.1" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: 28aa3175dc37c1a2c8008e1ec15cb46f67255b782d788cd0c40fa934d902e164

build:
  number: 0
  skip: true  # [(win and py27) or win32]

requirements:
  build:
    - toolchain
    - cmake
    - eigen
    - nlopt
    - boost     1.63.*
    - numpy     x.x
    - dill
    - ipyparallel
    - python
  run:
    - nlopt
    - boost     1.63.*
    - numpy     x.x
    - dill
    - ipyparallel
    - python

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - xantares
    - ccordoba12
    - bluescarni
    - darioizzo
