{% set version = "2.3" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: 22a225801c0f484accfe0edfe6ae0618a460cce0aada6b3b4fc5ee891a2f9e43

build:
  number: 0
  skip: true  # [(win and py27) or win32]

requirements:
  build:
    - toolchain
    - cmake
    - eigen
    - nlopt
    - boost     1.63.*
    - numpy     x.x
    - cloudpickle
    - ipyparallel
    - python
    - ipopt             # [unix]
  run:
    - nlopt
    - boost     1.63.*
    - numpy     x.x
    - cloudpickle
    - ipyparallel
    - python
    - ipopt             # [unix]

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - xantares
    - ccordoba12
    - bluescarni
    - darioizzo
