{% set version = "2.11.3" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: 5ba37ee671951e12c487932f0c26f647926dd133133cc5a1dd59d481bcc7e896

build:
  number: 0
  skip: true  # [(win and py<35) or win32]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pagmo     {{ version }}
    - boost
    - boost-cpp
    - numpy
    - cloudpickle
    - ipyparallel
    - python
  run:
    - pagmo     {{ version }}
    - boost
    - boost-cpp
    - {{ pin_compatible('numpy') }}
    - cloudpickle
    - ipyparallel
    - python

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - ccordoba12
    - bluescarni
    - darioizzo
