{% set version = "2.14.0" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pygmo2/archive/v{{ version }}.tar.gz
  sha256: 72000a0c6bd22b8955a65ebfcb53a8f42e8b00fd16afc0b7b43ef74b14883d60

build:
  number: 1
  skip: true  # [py<35]
  ignore_run_exports:
    # pagmo-devel will automatically
    # put nlopt and ipopt as run dependencies,
    # but we don't actually need any symbol
    # from these libraries in pygmo's module.
    # Thus, remove them from the runtime
    # requirements.
    - nlopt
    - ipopt  # [unix]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - vs2017_{{ target_platform  }}    # [win]
  host:
    - pagmo-devel
    - boost-cpp
    - numpy
    - cloudpickle
    - ipyparallel  # [py<38]
    - python
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - {{ pin_compatible('numpy') }}
    - cloudpickle
    - ipyparallel  # [py<38]
    - python

about:
  home: https://esa.github.io/pygmo2/
  license: MPL-2.0
  license_file: LICENSE
  summary: A Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model

extra:
  recipe-maintainers:
    - ccordoba12
    - bluescarni
    - darioizzo
