{% set version = "2.7" %}

package:
  name: pygmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: cbb29022057185dff81958cfec8ba15b700ffc45bc5caf87fd6676f37e3b6f8f

build:
  number: 0
  skip: true  # [(win and py<36) or win32]

requirements:
  build:
    - toolchain
    - cmake
    - pagmo     {{ version }}
    - eigen
    - nlopt
    - boost     1.66.0
    - numpy     x.x
    - cloudpickle
    - ipyparallel
    - python
    - ipopt             # [unix]
  run:
    - pagmo     {{ version }}
    - nlopt
    - boost     1.66.0
    - numpy     x.x
    - cloudpickle
    - ipyparallel
    - python
    - ipopt             # [unix]

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - xantares
    - ccordoba12
    - bluescarni
    - darioizzo
