travis:
  secure:
    BINSTAR_TOKEN: LZUm5KMobbH9BofWTkkUG6PLjJkdpJVMRsHWMKEewq3ubFed2MyCIxX5udCA1102u0fVwTSYfFEpy7f6umu3O228QAKreDqnSZ1TVN8JEXIkQkI/VxfEiX7SSKmdwMt5si0Z9gY7nTr8SFdxeowyfPvjFkwMjF/ScRpVORPe7pLI7E0uUkMWpg0kV9/HtWGkJrlQPdjg03vlTymGFnmoXTh7YT1oCGK89XKZu3lJPK+9ZLIsmnwMpShmmkJuHMfr4L0v2+L/FD3UqigplWz6Fv/ZvhHRINes2MBTyK1zh6p5uAGyysc2BoGuQ/GMVZ2byxd3zA7CrHYe3gXyWe4yEUgT4EDoQXxbR7zKt7VneJgtNtaWShoIP86TQTl1EbjOzrREwTOZq+vyhX/bZMJntjBLTEUwfueO89YlHtEyb/m5V51/QIVqKvcj0LPIpmI8+ide8lCP4hYSkaqzF/Fi8e1AcneD+kSkK/Lht4q86eC5vlGKskTdJnDJaNa40io+UsN5cgGwraXMg1mhWu7XIlIBMjwepjqxhDcusbhuadynyNd3v3gm+2F9sw+6BjxgFcpPtvsXusWXQ9SBOy4VDJWZrrton+7MMTHbiyvfumixFYX1iJ77czPgqfBwGFkXC1X+BcW9laD7jncJdthC/Dype0SNuXn+DaE4fCt0qHU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
